/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Material Design 3 tokens (from Stitch brutalist design)
        "tertiary-fixed": "var(--color-tertiary-fixed, #ffdf93)",
        "surface-container-high": "var(--color-surface-container-high, #ece6ee)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant, #594400)",
        "tertiary-container": "var(--color-tertiary-container, #c9a74d)",
        "surface-bright": "var(--color-surface-bright, #fdf7ff)",
        "surface-variant": "var(--color-surface-variant, #e6e0e9)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim, #e7c365)",
        "on-secondary": "var(--color-on-secondary, #ffffff)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim, #cfbcff)",
        "surface-container": "var(--color-surface-container, #f2ecf4)",
        "on-error": "var(--color-on-error, #ffffff)",
        primary: "var(--color-primary, #4f378a)",
        "on-background": "var(--color-on-background, #1d1b20)",
        "error-container": "var(--color-error-container, #ffdad6)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant, #4f378a)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim, #cdc0e9)",
        error: "var(--color-error, #ba1a1a)",
        tertiary: "var(--color-tertiary, #765b00)",
        "primary-fixed": "var(--color-primary-fixed, #e9ddff)",
        "surface-container-low": "var(--color-surface-container-low, #f8f2fa)",
        "on-primary": "var(--color-on-primary, #ffffff)",
        "on-tertiary": "var(--color-on-tertiary, #ffffff)",
        "surface-tint": "var(--color-surface-tint, #6750a4)",
        "on-surface-variant": "var(--color-on-surface-variant, #494551)",
        "secondary-fixed": "var(--color-secondary-fixed, #e9ddff)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed, #1f1635)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant, #4b4263)",
        "inverse-surface": "var(--color-inverse-surface, #322f35)",
        "on-primary-container": "var(--color-on-primary-container, #e0d2ff)",
        outline: "var(--color-outline, #7a7582)",
        surface: "var(--color-surface, #fdf7ff)",
        "primary-container": "var(--color-primary-container, #6750a4)",
        "secondary-container": "var(--color-secondary-container, #e1d4fd)",
        "surface-container-highest": "var(--color-surface-container-highest, #e6e0e9)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed, #241a00)",
        secondary: "var(--color-secondary, #63597c)",
        "on-primary-fixed": "var(--color-on-primary-fixed, #22005d)",
        "on-surface": "var(--color-on-surface, #1d1b20)",
        "inverse-primary": "var(--color-inverse-primary, #cfbcff)",
        "on-error-container": "var(--color-on-error-container, #93000a)",
        "inverse-on-surface": "var(--color-inverse-on-surface, #f5eff7)",
        "surface-dim": "var(--color-surface-dim, #ded8e0)",
        "surface-container-lowest": "var(--color-surface-container-lowest, #ffffff)",
        "on-tertiary-container": "var(--color-on-tertiary-container, #503d00)",
        "outline-variant": "var(--color-outline-variant, #cbc4d2)",
        "on-secondary-container": "var(--color-on-secondary-container, #645a7d)",
        background: "var(--color-background, #fdf7ff)",
        // Accent
        ink: "var(--color-ink, #2A2A2A)",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Public Sans", "sans-serif"],
        display: ["Public Sans", "sans-serif"],
        body: ["Public Sans", "sans-serif"],
        label: ["Public Sans", "sans-serif"],
        serif: ["DM Serif Display", "serif"],
        mono: ["IBM Plex Mono", "monospace"],
        grotesk: ["Space Grotesk", "sans-serif"],
      },
      boxShadow: {
        brutal: "4px 4px 0px 0px #2A2A2A",
        "brutal-sm": "2px 2px 0px 0px #2A2A2A",
        "brutal-lg": "6px 6px 0px 0px #2A2A2A",
        "brutal-primary": "4px 4px 0px 0px #4f378a",
      },
      animation: {
        "fade-in": "fadeIn 0.3s ease-in-out",
        "slide-up": "slideUp 0.4s ease-out",
        "pulse-slow": "pulse 3s infinite",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
    },
  },
  plugins: [],
};
