"""add portfolio customization fields and username

Revision ID: 6405eef15544
Revises: 82704ad10af7
Create Date: 2026-07-10 13:35:43.946068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6405eef15544'
down_revision = '82704ad10af7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('portfolio_bg_color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('portfolio_text_color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('portfolio_accent_color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('portfolio_card_color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('portfolio_font', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('portfolio_font')
        batch_op.drop_column('portfolio_card_color')
        batch_op.drop_column('portfolio_accent_color')
        batch_op.drop_column('portfolio_text_color')
        batch_op.drop_column('portfolio_bg_color')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
