"""Add location to Student

Revision ID: 72eddc8766df
Revises: 6405eef15544
Create Date: 2026-07-13 13:59:59.837754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72eddc8766df'
down_revision = '6405eef15544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###
