"""add readme field to project

Revision ID: 82704ad10af7
Revises: dc3aa3c47ea5
Create Date: 2026-07-09 13:00:16.264225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82704ad10af7'
down_revision = 'dc3aa3c47ea5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('readme', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('readme')

    # ### end Alembic commands ###
