"""Add message edit fields

Revision ID: 92db83cad690
Revises: 08eef7f11ae0
Create Date: 2026-07-24 16:59:33.604478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92db83cad690'
down_revision = '08eef7f11ae0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_edited', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('edited_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('edited_at')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('is_edited')

    # ### end Alembic commands ###
