"""add portfolio template field

Revision ID: dc3aa3c47ea5
Revises: b75eff003a3a
Create Date: 2026-07-09 12:12:08.425669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc3aa3c47ea5'
down_revision = 'b75eff003a3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('portfolio_template', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('portfolio_template')

    # ### end Alembic commands ###
